# Generated by Django 6.0.5 on 2026-06-03 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('unit', models.CharField(default='Unidad', max_length=50, verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='executed_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas Ejecutadas'),
        ),
        migrations.AddField(
            model_name='task',
            name='involved_persons',
            field=models.ManyToManyField(blank=True, related_name='involved_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Personas Involucradas'),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Horas Planificadas'),
        ),
        migrations.CreateModel(
            name='TaskResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Cantidad')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_resources', to='tasks.article', verbose_name='Artículo')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tasks.task', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Recurso de Tarea',
                'verbose_name_plural': 'Recursos de Tarea',
            },
        ),
    ]
